### ISSUE TITLE
Error when invoking the endpoint with boto3

### ISSUE THREAD

**Issue by franz101** [shashankprasanna/torchserve-examples#3]
Great tutorial. Though I'm currently am not able to invoke the endpoint correctly

An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message "{
  "code": 400,
  "type": "BadRequestException",
  "message": "Parameter model_name is required."
}

Seems like 
localhost:8080/predictions/{model_name}
is not getting called.

**Comment by shashankprasanna** [comment]
Hi fraz101, I just re-ran the entire notebook and can confirm that the example ran fine without issues.
Were you able to get predictions using the SageMaker SDK? is the issue only with the boto3 API? (both approaches are included in the notebook)

From the error it seems like you may be trying to deploy a multi-model endpoint. While this is supported by SageMaker, and also supported by TorchServe, it's not currently supported by "TorchServe on SageMaker". In this example we're deploying TorchServe as a custom user-built container and SageMaker treats it as a single model endpoint.

**Comment by franz101** [comment]
Thank you for your quick reply. I also reran everything and was able to deploy the project. Amazing tutorial. Keep up the good work :)

**Comment by Amiram1** [comment]
Hey @shashankprasanna,
I'm also getting the same error. I'm using a model archive file that works fine with torchserve locally, but when trying the same process as described in the notebook I'm getting the same:

`botocore.errorfactory.ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message "{
  "code": 400,
  "type": "BadRequestException",
  "message": "Parameter model_name is required."
}`

I tried both the sagemaker sdk and boto3 api and made sure the model is in a Single model mode

Any ideas how to fix/debug this?

Thanks!

**Comment by twhelan1999** [comment]
I am having the exact same issues. I would love to find a solution as well!

**Comment by shashankprasanna** [comment]
@Amiram1 @twhelan1999 - I just reran the demo and it works fine on my end. I ran the example on Amazon SageMaker notebook instance, using the default conda_python3 conda environment. I also just updated the notebook to work with Amazon SageMaker SDK 2.0 which released yesterday, and will automatically install when you run the first cell with pip install sagemaker --upgrade.

Could you try it on SageMaker notebook instance described above? I've only tested this example on this environment.
Follow the accompanying blog post for setting up permissions to access ECR:
https://aws.amazon.com/blogs/machine-learning/deploying-pytorch-models-for-inference-at-scale-using-torchserve/

**Comment by Amiram1** [comment]
Thanks, my error ended up being that I archived the .mar inside a model_store dir:
`tar cvfz <model_name>.tar.gz model_store/<model_name>.mar`

It needs to be in the top level. @twhelan1999 , maybe this could help you.

Still having problems installing additional dependencies, but that should be easier to solve.

**Comment by dectl** [comment]
Having the same problem...
